version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/globalmart-catalog
    overwrite: yes
permissions:
  - object: /home/ec2-user/globalmart-catalog
    owner: ec2-user
    group: ec2-user
  - object: /home/ec2-user/globalmart-catalog/scripts
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 600
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root