version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "=== Installing dependencies ==="
      - node --version
      - npm --version
      - npm ci
      - chmod -R 755 node_modules/.bin/
  
  build:
    commands:
      - echo "=== Building React Application ==="
      - echo "🧹 Clearing ALL caches..."
      - rm -rf build/ node_modules/.cache/ ~/.npm/_cacache/
      - export CI=false
      - export NODE_ENV=production  
      - export GENERATE_SOURCEMAP=false
      - export REACT_APP_BUILD_TIME=$(date +%Y%m%d-%H%M%S)
      - export REACT_APP_COMMIT_HASH=$(git rev-parse --short HEAD)
      - export REACT_APP_BUILD_NUMBER=$CODEBUILD_BUILD_NUMBER
      - export REACT_APP_PIPELINE_ID=$(uuidgen | cut -c1-8)
      - echo "🔨 Build Info:"
      - echo "  Timestamp: $REACT_APP_BUILD_TIME"
      - echo "  Commit: $REACT_APP_COMMIT_HASH"  
      - echo "  Build #: $REACT_APP_BUILD_NUMBER"
      - echo "  Pipeline ID: $REACT_APP_PIPELINE_ID"
      - npm run build --verbose
      - echo "✅ Build completed with cache-busting"
      - echo "Build completed successfully"
      - ls -la build/static/js/ | head -5
      - test -f build/index.html && echo "✅ index.html created" || exit 1

artifacts:
  files:
    - 'build/**/*'
    - 'scripts/**/*' 
    - 'appspec.yml'
  name: globalmart-build-$CODEBUILD_BUILD_NUMBER