version: 0.2

env:
  variables:
    NODE_VERSION: "20.18.0"

phases:
  install:
    commands:
      - echo "=== CUSTOM NODE.JS INSTALLATION ==="
      - echo "Current Node.js version:" && node --version || echo "Node.js not found"
      - echo "Installing Node.js ${NODE_VERSION}..."
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
      - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      - nvm install ${NODE_VERSION}
      - nvm use ${NODE_VERSION}
      - nvm alias default ${NODE_VERSION}
      - echo "New Node.js version:" && node --version
      - echo "npm version:" && npm --version
      - echo "Installing dependencies..."
      - npm install
      - echo "Setting executable permissions..."
      - chmod -R +x node_modules/.bin/
  
  pre_build:
    commands:
      - echo "=== PRE-BUILD VERIFICATION ==="
      - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      - nvm use ${NODE_VERSION}
      - echo "Node.js version:" && node --version
      - echo "npm version:" && npm --version
      - echo "react-scripts location and permissions:"
      - ls -la node_modules/.bin/react-scripts
      - echo "Testing react-scripts:"
      - npx react-scripts --version
  
  build:
    commands:
      - echo "=== BUILD PHASE ==="
      - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      - nvm use ${NODE_VERSION}
      - echo "Building React application..."
      - CI=false npx react-scripts build
      - echo "Build completed successfully!"
      - echo "Build output verification:"
      - ls -la build/
      - test -f build/index.html && echo "SUCCESS - Build artifacts created" || echo "ERROR - Build failed" && exit 1
  
  post_build:
    commands:
      - echo "=== POST-BUILD ==="
      - echo "Final verification:"
      - ls -la build/
      - du -sh build/

artifacts:
  files:
    - 'build/**/*'
    - 'scripts/**/*'
    - 'appspec.yml'
  name: globalmart-catalog-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    - '$HOME/.nvm/**/*'
    - 'node_modules/**/*'