version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "INSTALL PHASE - Installing dependencies"
      - npm ci
      - chmod -R +x node_modules/.bin/
  
  build:
    commands:
      - echo "BUILD PHASE - Building React app"
      - export CI=false
      - export NODE_ENV=production  
      - node node_modules/react-scripts/bin/react-scripts.js build
      - ls -la build/
  
  post_build:
    commands:
      - echo "=== POST-BUILD ==="
      - echo "Final verification:"
      - ls -la build/
      - du -sh build/

artifacts:
  files:
    - 'build/**/*'
    - 'scripts/**/*'
    - 'appspec.yml'
  name: globalmart-catalog-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    - '$HOME/.nvm/**/*'
    - 'node_modules/**/*'